#!/usr/bin/env bash

set -uexo pipefail

export resolution=$(xrandr | awk '/\*/ {print $1; exit}')
export refresh=$(xrandr | sed -En 's/.* ([0-9.]+)\*.*/\1/p')
export width=${resolution%x*}
export height=${resolution#*x}

# reads mangoapp wrapper script from this dir
export PATH=/usr/local/libexec/gamescope:$PATH

# share same data dir with flatpaked steam
export XDG_DATA_HOME=$HOME/.var/app/com.valvesoftware.Steam/.local/share

# --tmpfs $HOME/.steam   - ignore previously configured data dir and force $XDG_DATA_HOME path
# --tmpfs /tmp/.X11-unix - required for gamescope to work inside container
exec bwrap \
  --dev-bind / / \
  --tmpfs $HOME/.steam \
  --tmpfs /tmp/.X11-unix \
  /usr/bin/gamescope \
  --backend=wayland \
  --expose-wayland \
  --steam \
  --mangoapp \
  --fullscreen \
  --output-width=$width \
  --output-height=$height \
  --nested-refresh=$refresh \
  -- \
  /usr/bin/steam
